In [77]:
import numpy as np


A = np.array([[2,1,1],\
     [0,1/2,-5/2],
     [0,0,40]])

paso_i = 0
paso_j = 0

for i in A:
  paso_i+=1
  #print("Paso en i" +str(paso_i) + ":" + str(i))

  for j in A:
    paso_j+=1
    #print("Paso en j" +str(paso_j) + ":" + str(j))


In [78]:
A = np.array([[2,1,1]])

for i in A:
  print(i)
  test = zip(A)
  print(test)

[2 1 1]


In [79]:
B = np.zeros(5)

print(B)

[0. 0. 0. 0. 0.]


In [80]:
C = np.array([[1,2,-1],
             [1,0,1],
             [4,-4,5]])

ValoresP, VectoresP = np.linalg.eig(C)

print("Los valores propios son: " + str(ValoresP))

print("Los vectores propios: " + str(VectoresP))

Los valores propios son: [3. 2. 1.]
Los vectores propios: [[-0.23570226  0.43643578  0.40824829]
 [ 0.23570226 -0.21821789 -0.40824829]
 [ 0.94280904 -0.87287156 -0.81649658]]


In [81]:
A = np.array([1,2,-1])

B = np.array([3,1,2])

AB = np.dot(A, B)

print(AB)

3


In [82]:
#k_11 = k_22 = k_33 = -2*k

A = 2

#k_12 = k_21 = k_23 = k_32 = k

B = 4

#k_13 = k_31 = 0

C = 6



M = np.array([[A,B,C],
             [B,A,B],
             [C,B,A]])

print(M)

[[2 4 6]
 [4 2 4]
 [6 4 2]]


In [142]:
#Desde aca hasta la ultima es el problema:

q_0 = np.array([2,2,2])

A = np.array([[1,2,-1],
             [1,0,1],
             [4,-4,5]])
#Esta fue la matriz de prueba

def valor_p(A,q0,tolerancia=2):
  z_1 = A @ q_0
  q_1=0
  #Tambien servia z_1 = np.linalg.dot(A,q_0)
  for i in range(int(1e5)):
    norm_z =np.linalg.norm(z_1)
    q_1 = z_1 / norm_z

    Miu = q_1.T @ A @ q_1
    z_1= A @ q_1

  return np.round(Miu, tolerancia), q_1


In [143]:
max, vmax=valor_p(A,q_0)

min, vmin= valor_p(np.linalg.inv(A),q_0)

In [144]:
print(max,vmax)
print(1/min,vmin)

3.0 [-0.23570226  0.23570226  0.94280904]
1.0 [-0.40824829  0.40824829  0.81649658]


In [145]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [146]:
M_1 = 2

M_2 = 3

M_3 = 4



k_11, k_22, k_33 = -2,-2,-2

k_12, k_21, k_23, k_32 = 1,1,1,1

k_13, k_31 = 0,0


M = np.array([[k_11/M_1,k_12/M_1,k_13/M_1],
             [k_21/M_2,k_22/M_2,k_23/M_2],
             [k_31/M_3,k_32/M_3,k_33/M_3]])

maximo_valor , maximo_vector = valor_p(-M,q_0)

minimo_valor , minimo_vector = valor_p(-np.linalg.inv(M),q_0)

print(np.round(np.sqrt(maximo_valor),2) , maximo_vector, np.sqrt(1/minimo_valor) , minimo_vector)

#El valor maximo y el minimo del problema dan valores un poco alejados a lo que me arroja np.linalg.eig(), contrario a la martriz de prueba la cual si da valores exactos en ambas.

1.14 [ 0.83964254 -0.51892763  0.16035746] 0.43685202833051895 [0.43308473 0.70074581 0.56691527]


In [147]:
valores,vectores=np.linalg.eigh(-M)
np.sqrt(valores)


array([0.50822168, 0.8226171 , 1.10981012])